# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import csv

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def searchClicked(self):

        self.personInfo.clear()
        self.recordBrowser.clear()
        queriedPerson = self.searchBox.toPlainText()
        workerID = 9999
        found = False

        print("searchClicked success")


        with open("exampleDB.csv", "r") as workerList:

            if queriedPerson.isnumeric() == True:
                for line in csv.reader(workerList):
                    if queriedPerson == line[0]:
                        workerID = line[0]
                        self.personInfo.setText("Worker ID: " + line[0] +
                                                 "\nFirst Name: " + line[1] +
                                                 "\nLast Name: " + line[2] +
                                                 "\nAccess level: " + line[3])
                        found = True
                        self.populateRecords(workerID)

                        break

                    else:
                        found = False

            elif queriedPerson.isnumeric() == False:
                for line in csv.reader(workerList):
                    if queriedPerson == line[1]:
                        workerID = line[0]
                        self.personInfo.setText("Worker ID: " + line[0] +
                                                 "\nFirst Name: " + line[1] +
                                                 "\nLast Name: " + line[2] +
                                                 "\nAccess level: " + line[3])
                        found = True
                        self.populateRecords(workerID)
                        break

                    elif queriedPerson == line[2]:
                        workerID = line[0]
                        self.personInfo.setText("Worker ID: " + line[0] +
                                                 "\nFirst Name: " + line[1] +
                                                 "\nLast Name: " + line[2] +
                                                 "\nAccess level: " + line[3])
                        found = True
                        self.populateRecords(workerID)
                        break

                    else:
                        found = False

        if found != True:
            self.personInfo.clear()
            self.recordBrowser.clear()





    def populateRecords(self, workerID):
        try:
            with open(str(workerID) + ".csv", "r") as workerRecords:
                for line in csv.reader(workerRecords):
                    self.recordBrowser.append(line[0] + "  " + line[1] + "  " + line[2])
        except:
            self.recordBrowser.setText("FAILED TO LOAD")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(390, 10, 181, 51))
        self.searchButton.setObjectName("searchButton")
        self.searchBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.searchBox.setGeometry(QtCore.QRect(20, 10, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchBox.setFont(font)
        self.searchBox.setObjectName("searchBox")
        self.personInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.personInfo.setGeometry(QtCore.QRect(20, 100, 551, 381))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.personInfo.setFont(font)
        self.personInfo.setObjectName("personInfo")
        self.analysisOut = QtWidgets.QTextBrowser(self.centralwidget)
        self.analysisOut.setGeometry(QtCore.QRect(20, 520, 551, 631))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.analysisOut.setFont(font)
        self.analysisOut.setObjectName("analysisOut")
        self.recordBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.recordBrowser.setGeometry(QtCore.QRect(590, 60, 581, 1091))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.recordBrowser.setFont(font)
        self.recordBrowser.setObjectName("recordBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(590, 10, 500, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 480, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.searchButton.clicked.connect(self.searchClicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Personal check-in records"))
        self.label_2.setText(_translate("MainWindow", "Personal info"))
        self.label_3.setText(_translate("MainWindow", "Attendance analysis"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
